export interface ThemePalette {
  bgBase: string | undefined;
  bgSurface: string | undefined;
  bgElement: string | undefined;
  bgHeader: string | undefined;
  fgBase: string | undefined;
  fgSub: string | undefined;
  fgDim: string | undefined;
  borderBase: string | undefined;
  borderFocus: string | undefined;
  itemFocus: string | undefined;
  itemSelect: string | undefined;
  itemMarker: string | undefined;
  progress: string | undefined;
  keyBind: string | undefined;
  statError: string | undefined;
  statWarn: string | undefined;
  statSuccess: string | undefined;
  statInfo: string | undefined;
}

const SystemPalette: ThemePalette = {
  bgBase: "transparent",
  bgSurface: "black",
  bgElement: "transparent",
  bgHeader: "black",
  fgBase: "white",
  fgSub: "white",
  fgDim: "white",
  borderBase: "white",
  borderFocus: "cyan",
  itemFocus: "cyan",
  itemSelect: "white",
  itemMarker: "red",
  progress: "green",
  keyBind: "yellow",
  statError: "red",
  statWarn: "yellow",
  statSuccess: "green",
  statInfo: "cyan",
};

const CatppuccinPalette: ThemePalette = {
  bgBase: "#1e1e2e",
  bgSurface: "#181825",
  bgElement: "#313244",
  bgHeader: "#6b5885",
  fgBase: "#cdd6f4",
  fgSub: "#bac2de",
  fgDim: "#a6adc8",
  borderBase: "#45475a",
  borderFocus: "#f5c2e7",
  itemFocus: "#cba6f7",
  itemSelect: "#f2cdcd",
  itemMarker: "#fab387",
  progress: "#cba6f7",
  keyBind: "#f9e2af",
  statError: "#f38ba8",
  statWarn: "#f9e2af",
  statSuccess: "#a6e3a1",
  statInfo: "#89b4fa",
};

const CyberdreamPalette: ThemePalette = {
  bgBase: "#16181a",
  bgSurface: "#1e2124",
  bgElement: "#3c4048",
  bgHeader: "#16181a",
  fgBase: "#ffffff",
  fgSub: "#7b8496",
  fgDim: "#3c4048",
  borderBase: "#1e2124",
  borderFocus: "#5ea1ff",
  itemFocus: "#5ea1ff",
  itemSelect: "#3c4048",
  itemMarker: "#ffbd5e",
  progress: "#5ea1ff",
  keyBind: "#ffbd5e",
  statError: "#ff6e5e",
  statWarn: "#f1ff5e",
  statSuccess: "#5eff6c",
  statInfo: "#5ef1ff",
};

const DraculaPalette: ThemePalette = {
  bgBase: "#282a36",
  bgSurface: "#21222c",
  bgElement: "#44475a",
  bgHeader: "#44475a",
  fgBase: "#f8f8f2",
  fgSub: "#6272a4",
  fgDim: "#6272a4",
  borderBase: "#4d4f68",
  borderFocus: "#bd93f9",
  itemFocus: "#bd93f9",
  itemSelect: "#ff79c6",
  itemMarker: "#ffb86c",
  progress: "#50fa7b",
  keyBind: "#f1fa8c",
  statError: "#ff5555",
  statWarn: "#ffb86c",
  statSuccess: "#50fa7b",
  statInfo: "#8be9fd",
};

const GruvboxPalette: ThemePalette = {
  bgBase: "#282828",
  bgSurface: "#3c3836",
  bgElement: "#504945",
  bgHeader: "#3c3836",
  fgBase: "#ebdbb2",
  fgSub: "#bdae93",
  fgDim: "#a89984",
  borderBase: "#504945",
  borderFocus: "#fe8019",
  itemFocus: "#fe8019",
  itemSelect: "#fabd2f",
  itemMarker: "#d65d0e",
  progress: "#b8bb26",
  keyBind: "#fabd2f",
  statError: "#fb4934",
  statWarn: "#fabd2f",
  statSuccess: "#b8bb26",
  statInfo: "#83a598",
};

const KanagawaPalette: ThemePalette = {
  bgBase: "#1f1f28",
  bgSurface: "#1f1f28",
  bgElement: "#2a2a37",
  bgHeader: "#1f1f28",
  fgBase: "#dcd7ba",
  fgSub: "#c8c093",
  fgDim: "#727169",
  borderBase: "#223249",
  borderFocus: "#7e9cd8",
  itemFocus: "#7e9cd8",
  itemSelect: "#957fb8",
  itemMarker: "#ffa066",
  progress: "#7e9cd8",
  keyBind: "#e6c384",
  statError: "#c34043",
  statWarn: "#ffa066",
  statSuccess: "#76946a",
  statInfo: "#7fb4ca",
};

const KansoPalette: ThemePalette = {
  bgBase: "#14171d",
  bgSurface: "#1f1f26",
  bgElement: "#393b44",
  bgHeader: "#14171d",
  fgBase: "#c5c9c7",
  fgSub: "#9ca6a6",
  fgDim: "#717c7c",
  borderBase: "#22262d",
  borderFocus: "#7fb4ca",
  itemFocus: "#7fb4ca",
  itemSelect: "#223249",
  itemMarker: "#dca561",
  progress: "#98bb6c",
  keyBind: "#dca561",
  statError: "#c34043",
  statWarn: "#dca561",
  statSuccess: "#98bb6c",
  statInfo: "#7fb4ca",
};

const MonokaiPalette: ThemePalette = {
  bgBase: "#272822",
  bgSurface: "#221f22",
  bgElement: "#3e3d32",
  bgHeader: "#403e41",
  fgBase: "#fcfcfa",
  fgSub: "#75715e",
  fgDim: "#75715e",
  borderBase: "#49483e",
  borderFocus: "#a6e22e",
  itemFocus: "#ffd866",
  itemSelect: "#ab9df2",
  itemMarker: "#fd971f",
  progress: "#a6e22e",
  keyBind: "#e6db74",
  statError: "#f92672",
  statWarn: "#fd971f",
  statSuccess: "#a6e22e",
  statInfo: "#66d9ef",
};

const NordPalette: ThemePalette = {
  bgBase: "#2e3440",
  bgSurface: "#3b4252",
  bgElement: "#434c5e",
  bgHeader: "#3b4252",
  fgBase: "#d8dee9",
  fgSub: "#e5e9f0",
  fgDim: "#eceff4",
  borderBase: "#434c5e",
  borderFocus: "#88c0d0",
  itemFocus: "#88c0d0",
  itemSelect: "#81a1c1",
  itemMarker: "#d08770",
  progress: "#a3be8c",
  keyBind: "#ebcb8b",
  statError: "#bf616a",
  statWarn: "#ebcb8b",
  statSuccess: "#a3be8c",
  statInfo: "#81a1c1",
};

const OneDarkPalette: ThemePalette = {
  bgBase: "#282c34",
  bgSurface: "#21252b",
  bgElement: "#2c313a",
  bgHeader: "#21252b",
  fgBase: "#abb2bf",
  fgSub: "#828997",
  fgDim: "#5c6370",
  borderBase: "#3e4451",
  borderFocus: "#61afef",
  itemFocus: "#61afef",
  itemSelect: "#c678dd",
  itemMarker: "#d19a66",
  progress: "#98c379",
  keyBind: "#e5c07b",
  statError: "#e06c75",
  statWarn: "#e5c07b",
  statSuccess: "#98c379",
  statInfo: "#61afef",
};

const RosePinePalette: ThemePalette = {
  bgBase: "#191724",
  bgSurface: "#1f1d2e",
  bgElement: "#26233a",
  bgHeader: "#1f1d2e",
  fgBase: "#e0def4",
  fgSub: "#908caa",
  fgDim: "#6e6a86",
  borderBase: "#403d52",
  borderFocus: "#ebbcba",
  itemFocus: "#ebbcba",
  itemSelect: "#ebbcba",
  itemMarker: "#f6c177",
  progress: "#31748f",
  keyBind: "#f6c177",
  statError: "#eb6f92",
  statWarn: "#f6c177",
  statSuccess: "#31748f",
  statInfo: "#9ccfd8",
};

const SolarizedDarkPalette: ThemePalette = {
  bgBase: "#002b36",
  bgSurface: "#073642",
  bgElement: "#073642",
  bgHeader: "#002b36",
  fgBase: "#839496",
  fgSub: "#93a1a1",
  fgDim: "#586e75",
  borderBase: "#073642",
  borderFocus: "#93a1a1",
  itemFocus: "#2aa198",
  itemSelect: "#586e75",
  itemMarker: "#cb4b16",
  progress: "#2aa198",
  keyBind: "#b58900",
  statError: "#dc322f",
  statWarn: "#b58900",
  statSuccess: "#859900",
  statInfo: "#268bd2",
};

const TokyoNightPalette: ThemePalette = {
  bgBase: "#1a1b26",
  bgSurface: "#1f2335",
  bgElement: "#24283b",
  bgHeader: "#1a1b26",
  fgBase: "#c0caf5",
  fgSub: "#a9b1d6",
  fgDim: "#565f89",
  borderBase: "#414868",
  borderFocus: "#7aa2f7",
  itemFocus: "#7aa2f7",
  itemSelect: "#bb9af7",
  itemMarker: "#7dcfff",
  progress: "#7aa2f7",
  keyBind: "#ff9e64",
  statError: "#db4b4b",
  statWarn: "#e0af68",
  statSuccess: "#9ece6a",
  statInfo: "#7aa2f7",
};

const ZenburnPalette: ThemePalette = {
  bgBase: "#3f3f3f",
  bgSurface: "#4f4f4f",
  bgElement: "#5f5f5f",
  bgHeader: "#4f4f4f",
  fgBase: "#dcdccc",
  fgSub: "#9faf9f",
  fgDim: "#7f7f7f",
  borderBase: "#5f5f5f",
  borderFocus: "#f0dfaf",
  itemFocus: "#f0dfaf",
  itemSelect: "#dc8cc3",
  itemMarker: "#dfaf8f",
  progress: "#7f9f7f",
  keyBind: "#f0dfaf",
  statError: "#dca3a3",
  statWarn: "#f0dfaf",
  statSuccess: "#7f9f7f",
  statInfo: "#8cd0d3",
};

export const Palettes = {
  System: SystemPalette,
  Catppuccin: CatppuccinPalette,
  Cyberdream: CyberdreamPalette,
  Dracula: DraculaPalette,
  Gruvbox: GruvboxPalette,
  Kanagawa: KanagawaPalette,
  Kanso: KansoPalette,
  Monokai: MonokaiPalette,
  Nord: NordPalette,
  "One Dark": OneDarkPalette,
  "Rosé Pine": RosePinePalette,
  "Solarized Dark": SolarizedDarkPalette,
  "Tokyo Night": TokyoNightPalette,
  Zenburn: ZenburnPalette,
} as const;

export const createTheme = (palette: ThemePalette) => ({
  background: palette.bgBase,
  focused: palette.bgSurface,
  foreground: palette.fgBase,
  text: {
    primary: palette.fgBase,
    secondary: palette.fgSub,
    dim: palette.fgDim,
    inverse: palette.bgBase,
    error: palette.statError,
    warning: palette.statWarn,
    success: palette.statSuccess,
    accent: palette.itemFocus,
  },
  border: {
    focused: palette.borderFocus,
    unfocused: palette.borderBase,
    highlight: palette.itemSelect,
    info: palette.statInfo,
    error: palette.statError,
  },
  list: {
    focused: palette.itemFocus,
    selected: palette.itemSelect,
    focusedSelected: palette.borderFocus,
    markerSelected: palette.itemMarker,
    markerUnfocused: palette.itemFocus,
    scrollBarThumb: palette.itemFocus,
    scrollBarTrack: palette.bgElement,
  },
  header: {
    background: palette.bgHeader,
    text: palette.fgBase,
  },
  popup: {
    border: palette.borderFocus,
    background: palette.bgSurface,
  },
  progressBar: {
    filled: palette.progress,
    empty: palette.bgElement,
  },
  footer: {
    key: palette.keyBind,
    text: palette.fgDim,
    separator: palette.itemSelect,
  },
  status: {
    debug: palette.statError,
    drive: palette.itemSelect,
    app: palette.statInfo,
    new: palette.statSuccess,
    synced: palette.fgDim,
    error: palette.statError,
    warning: palette.statWarn,
    selected: palette.itemFocus,
  },
});
